###########
# site.url, site.title

url:   'http://nilshoffmann.github.io/maltcms-extension-module'
project.url:   'https://github.com/nilshoffmann/maltcms-extension-module'
title: 'Maltcms Extension Module'


########

markdown: kramdown

sass:
  sass_dir: css
  style: expanded

exclude:
- README.md

safe: true
lsi: false
